// Generated by HEXA Bootstrap Compiler
#include "runtime.c"


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    HexaVal a = hexa_args();
        hexa_print_val(hexa_add(hexa_str("argc="), hexa_to_string(hexa_int(hexa_len(a)))));
    printf("\n");
    HexaVal i = hexa_int(0);
    while (hexa_truthy(hexa_int((i).i < (hexa_int(hexa_len(a))).i))) {
                hexa_print_val(hexa_add(hexa_add(hexa_add(hexa_str("arg["), hexa_to_string(i)), hexa_str("]=")), hexa_array_get(a,(i).i)));
        printf("\n");
        i = hexa_add(i, hexa_int(1));
    }
    return 0;
}
