// Generated by HEXA Bootstrap Compiler
#include "runtime.c"


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    HexaVal xs = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_int(10)), hexa_int(20)), hexa_int(30)), hexa_int(40));
    HexaVal total = hexa_int(0);
    { HexaVal _arr=xs;
for(int _i=0;_i<_arr.arr.len;_i++){HexaVal x=_arr.arr.items[_i];
        total = hexa_add(total, x);
    }}
        hexa_print_val(hexa_str("sum ="));
    printf(" ");
    hexa_print_val(total);
    printf(" ");
    hexa_print_val(hexa_str("len ="));
    printf(" ");
    hexa_print_val(hexa_int(hexa_len(xs)));
    printf("\n");
    HexaVal name = hexa_str("GUT");
    HexaVal dim = hexa_int(24);
        hexa_print_val(hexa_format(hexa_str("{} dim = {}"), name));
    printf("\n");
    HexaVal s = hexa_format(hexa_str("J = {} = sigma*phi"), dim);
        hexa_print_val(s);
    printf("\n");
    return 0;
}
