// Generated by HEXA Bootstrap Compiler
#include "runtime.c"


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    HexaVal s = hexa_format(hexa_str("[{:<8}]"), hexa_str("SU(5)"));
        hexa_print_val(s);
    printf("\n");
    HexaVal r = hexa_format(hexa_str("[{:>2}]"), hexa_int(4));
        hexa_print_val(r);
    printf("\n");
    HexaVal f = hexa_format(hexa_str("[{:.4}]"), hexa_float(0.0028));
        hexa_print_val(f);
    printf("\n");
    HexaVal m = hexa_format(hexa_str("{} rank = {} vs {} = {}"), hexa_str("SU(5)"));
        hexa_print_val(m);
    printf("\n");
    return 0;
}
