// Generated by HEXA Bootstrap Compiler
.global _main
.align 4

_hexa_print_int:
    stp x29, x30, [sp, #-16]!
    mov x29, sp
    sub sp, sp, #32
    mov x9, x0
    cmp x0, #0
    b.ge .Lpi_pos
    neg x0, x0
.Lpi_pos:
    add x1, sp, #20
    mov x2, #0
    mov x3, #10
.Lpi_loop:
    udiv x4, x0, x3
    msub x5, x4, x3, x0
    add x5, x5, #48
    sub x1, x1, #1
    strb w5, [x1]
    add x2, x2, #1
    mov x0, x4
    cbnz x0, .Lpi_loop
    cmp x9, #0
    b.ge .Lpi_write
    sub x1, x1, #1
    mov w5, #45
    strb w5, [x1]
    add x2, x2, #1
.Lpi_write:
    mov x0, #1
    mov x16, #4
    svc #0x80
    mov w5, #10
    strb w5, [sp]
    mov x0, #1
    mov x1, sp
    mov x2, #1
    mov x16, #4
    svc #0x80
    add sp, sp, #32
    ldp x29, x30, [sp], #16
    ret

_main:
    stp x29, x30, [sp, #-16]!
    mov x29, sp
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
    // expr:StringLit
    bl _hexa_print_int
    // expr:StringLit
    bl _hexa_print_int
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
    // LetStmt
.Lwhile_0:
    mov x0, #4
    str x0, [sp, #-16]!
    // load i
    ldr x1, [sp], #16
    cmp x0, x1
    cset x0, lt
    cbz x0, .Lwend_0
    // LetStmt
    // expr:Index
    str x0, [sp, #-16]!
    // expr:Index
    ldr x1, [sp], #16
    cmp x0, x1
    cset x0, eq
    cbz x0, .Lelse_1
    // AssignStmt
    // AssignStmt
.Lelse_1:
    // load mark
    str x0, [sp, #-16]!
    // expr:StringLit
    str x0, [sp, #-16]!
    // expr:Index
    str x0, [sp, #-16]!
    // expr:StringLit
    str x0, [sp, #-16]!
    // expr:Index
    str x0, [sp, #-16]!
    // expr:StringLit
    str x0, [sp, #-16]!
    // expr:Index
    str x0, [sp, #-16]!
    // expr:StringLit
    str x0, [sp, #-16]!
    // expr:Index
    str x0, [sp, #-16]!
    // expr:StringLit
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    bl _hexa_print_int
    // AssignStmt
    b .Lwhile_0
.Lwend_0:
    // expr:StringLit
    bl _hexa_print_int
    // expr:StringLit
    bl _hexa_print_int
    // expr:StringLit
    str x0, [sp, #-16]!
    // load matches
    str x0, [sp, #-16]!
    ldr x0, [sp], #16
    bl _to_string
    str x0, [sp, #-16]!
    // expr:StringLit
    ldr x1, [sp], #16
    add x0, x0, x1
    ldr x1, [sp], #16
    add x0, x0, x1
    bl _hexa_print_int
    // expr:StringLit
    bl _hexa_print_int
    mov x0, #0
    ldp x29, x30, [sp], #16
    ret
