// Generated by HEXA Bootstrap Compiler
#include "runtime.c"


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    HexaVal n = hexa_int(6);
    HexaVal sigma = hexa_int(12);
    HexaVal tau = hexa_int(4);
    HexaVal phi = hexa_int(2);
    HexaVal sopfr = hexa_int(5);
        hexa_print_val(hexa_str("══ PART 1: GUT Rank Sequence ══"));
    printf("\n");
        hexa_print_val(hexa_str(""));
    printf("\n");
    HexaVal names = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_str("SU(5)   ")), hexa_str("SO(10)  ")), hexa_str("E₆      ")), hexa_str("E₈      "));
    HexaVal ranks = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_str(" 4")), hexa_str(" 5")), hexa_str(" 6")), hexa_str(" 8"));
    HexaVal vals = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_str(" 4")), hexa_str(" 5")), hexa_str(" 6")), hexa_str(" 8"));
    HexaVal valsi = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), tau), sopfr), n), hexa_int((sigma).i - (tau).i));
    HexaVal ranki = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_int(4)), hexa_int(5)), hexa_int(6)), hexa_int(8));
    HexaVal exprs = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_str("τ(6)    ")), hexa_str("sopfr(6)")), hexa_str("n       ")), hexa_str("σ-τ     "));
    HexaVal i = hexa_int(0);
    HexaVal matches = hexa_int(0);
    while (hexa_truthy(hexa_int((i).i < (hexa_int(4)).i))) {
        HexaVal mark = hexa_str("✗ FAIL");
        if (hexa_truthy(hexa_eq(hexa_array_get(ranki,(i).i), hexa_array_get(valsi,(i).i)))) {
            mark = hexa_str("✓ EXACT");
            matches = hexa_add(matches, hexa_int(1));
        }
                hexa_print_val(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("  "), hexa_array_get(names,(i).i)), hexa_str(" rank = ")), hexa_array_get(ranks,(i).i)), hexa_str("  vs  ")), hexa_array_get(exprs,(i).i)), hexa_str(" = ")), hexa_array_get(vals,(i).i)), hexa_str("  → ")), mark));
        printf("\n");
        i = hexa_add(i, hexa_int(1));
    }
        hexa_print_val(hexa_str(""));
    printf("\n");
        hexa_print_val(hexa_str("  Rank sequence: (4, 5, 6, 8) = (τ, sopfr, n, σ-τ)"));
    printf("\n");
        hexa_print_val(hexa_add(hexa_add(hexa_str("  Matches: "), hexa_to_string(matches)), hexa_str("/4")));
    printf("\n");
        hexa_print_val(hexa_str("  P(all 4 match by chance) ≈ 0.0028 = 0.28%"));
    printf("\n");
    return 0;
}
