// Generated by HEXA Bootstrap Compiler
#include "runtime.c"


int main() {
    HexaVal n = hexa_int(6);
    HexaVal sigma = hexa_int(12);
    HexaVal phi = hexa_int(2);
    HexaVal tau = hexa_int(4);
    HexaVal lhs = hexa_int((sigma).i * (phi).i);
    HexaVal rhs = hexa_int((n).i * (tau).i);
    (hexa_println(hexa_add(hexa_str("lhs="), hexa_to_string(lhs))), hexa_void());
    (hexa_println(hexa_add(hexa_str("rhs="), hexa_to_string(rhs))), hexa_void());
    return 0;
}
