// Generated by HEXA Bootstrap Compiler
#include "runtime.c"


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    HexaVal x = hexa_float(0.23);
    HexaVal y = hexa_pow(x, hexa_int(4));
        hexa_print_val(hexa_add(hexa_str("pow(0.23, 4) = "), hexa_to_string(y)));
    printf("\n");
    HexaVal s = hexa_sqrt(hexa_float(2.0));
        hexa_print_val(hexa_add(hexa_str("sqrt(2) = "), hexa_to_string(s)));
    printf("\n");
    HexaVal f = hexa_floor(hexa_float(3.7));
        hexa_print_val(hexa_add(hexa_str("floor(3.7) = "), hexa_to_string(f)));
    printf("\n");
    return 0;
}
