/// Ownership Proof Obligation Tracking
///
/// Tracks proof obligations generated by the lowering phase and
/// verified by the optimizer (P2: ownership_proof, P12: verify).
///
/// Each obligation records a specific ownership event (transfer, borrow, drop)
/// and its resolution status. Unresolved obligations at codegen time are errors.

use std::collections::HashMap;

/// Kind of ownership obligation
#[derive(Clone, Debug, PartialEq)]
pub enum ObligationKind {
    /// Value was moved: source register is now dead
    Transfer { from: usize, to: usize },
    /// Value was borrowed: source must remain valid
    Borrow { reg: usize, mutable: bool },
    /// Value's lifetime ended: register is dead after this point
    LifetimeEnd { reg: usize },
    /// Assertion that a register is still live and valid
    LivenessCheck { reg: usize },
}

/// Resolution status of an obligation
#[derive(Clone, Debug, PartialEq)]
pub enum Resolution {
    /// Not yet verified
    Pending,
    /// Verified by the optimizer (pass name recorded)
    Verified { by_pass: &'static str },
    /// Violated — error message
    Violated { reason: String },
}

/// A single proof obligation
#[derive(Clone, Debug)]
pub struct Obligation {
    pub kind: ObligationKind,
    pub block_id: usize,
    pub instr_index: usize,
    pub resolution: Resolution,
}

/// Proof obligation tracker for a single function
pub struct OwnershipProofTracker {
    obligations: Vec<Obligation>,
    /// Register -> current owner (block_id, instr_index)
    ownership_map: HashMap<usize, (usize, usize)>,
}

impl OwnershipProofTracker {
    pub fn new() -> Self {
        OwnershipProofTracker {
            obligations: Vec::new(),
            ownership_map: HashMap::new(),
        }
    }

    /// Record a transfer obligation
    pub fn record_transfer(&mut self, from: usize, to: usize, block_id: usize, instr_idx: usize) {
        self.obligations.push(Obligation {
            kind: ObligationKind::Transfer { from, to },
            block_id,
            instr_index: instr_idx,
            resolution: Resolution::Pending,
        });
        // Update ownership map
        self.ownership_map.remove(&from);
        self.ownership_map.insert(to, (block_id, instr_idx));
    }

    /// Record a borrow obligation
    pub fn record_borrow(&mut self, reg: usize, mutable: bool, block_id: usize, instr_idx: usize) {
        self.obligations.push(Obligation {
            kind: ObligationKind::Borrow { reg, mutable },
            block_id,
            instr_index: instr_idx,
            resolution: Resolution::Pending,
        });
    }

    /// Record a lifetime end
    pub fn record_lifetime_end(&mut self, reg: usize, block_id: usize, instr_idx: usize) {
        self.obligations.push(Obligation {
            kind: ObligationKind::LifetimeEnd { reg },
            block_id,
            instr_index: instr_idx,
            resolution: Resolution::Pending,
        });
        self.ownership_map.remove(&reg);
    }

    /// Mark an obligation as verified
    pub fn verify(&mut self, index: usize, pass_name: &'static str) {
        if let Some(ob) = self.obligations.get_mut(index) {
            ob.resolution = Resolution::Verified { by_pass: pass_name };
        }
    }

    /// Mark an obligation as violated
    pub fn violate(&mut self, index: usize, reason: String) {
        if let Some(ob) = self.obligations.get_mut(index) {
            ob.resolution = Resolution::Violated { reason };
        }
    }

    /// Check if a register is currently owned (live)
    pub fn is_live(&self, reg: usize) -> bool {
        self.ownership_map.contains_key(&reg)
    }

    /// Get all unresolved (pending) obligations
    pub fn pending(&self) -> Vec<(usize, &Obligation)> {
        self.obligations.iter().enumerate()
            .filter(|(_, ob)| matches!(ob.resolution, Resolution::Pending))
            .collect()
    }

    /// Get all violations
    pub fn violations(&self) -> Vec<(usize, &Obligation)> {
        self.obligations.iter().enumerate()
            .filter(|(_, ob)| matches!(ob.resolution, Resolution::Violated { .. }))
            .collect()
    }

    /// Total obligation count
    pub fn total(&self) -> usize {
        self.obligations.len()
    }

    /// Verified count
    pub fn verified_count(&self) -> usize {
        self.obligations.iter()
            .filter(|ob| matches!(ob.resolution, Resolution::Verified { .. }))
            .count()
    }
}

impl Default for OwnershipProofTracker {
    fn default() -> Self {
        Self::new()
    }
}
