#!/usr/bin/env python3
"""Phase 6 Batch B7 translation helper.

Applies author-reviewed exact-string Korean->English substitutions across
18 physics domain files. Substitutions are deterministic, ordered, and
limited to the shared template vocabulary used by the physics-domain
gold-standard harness. Per-file specifics (titles, one-line summaries,
and the free-form section §X BLOWUP) are handled manually via Edit after
this helper runs.

Usage:
  python3 scripts/phase6_b7_translate.py <file1> [<file2> ...]

The script is intentionally idempotent: every replacement uses
str.replace on an exact multi-char phrase. If the file has already been
translated, no replacement fires. After running, lint with:
  python3 tool/own_doc_lint.py --rule 1
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Author-reviewed exact-string translation pairs for the physics gold-standard
# template. Order matters: longer phrases first so sub-phrases do not
# pre-empt them.
# Each entry is (korean_exact, english).

PAIRS: list[tuple[str, str]] = [
    # Section headers (long forms first)
    ("## §1 WHY (이 기술이 당신의 삶을 바꾸는 방법)",
     "## §1 WHY (how this technology changes your life)"),
    ("## §2 COMPARE (현 기술 vs n=6) — 성능 비교 (ASCII)",
     "## §2 COMPARE (current tech vs n=6) — performance comparison (ASCII)"),
    ("## §3 REQUIRES (필요한 요소) — 선행 도메인",
     "## §3 REQUIRES (prerequisite elements) — upstream domains"),
    ("## §4 STRUCT (시스템 구조) — System Architecture (ASCII)",
     "## §4 STRUCT (system architecture) — System Architecture (ASCII)"),
    ("## §5 FLOW (데이터/에너지 플로우) — Flow (ASCII)",
     "## §5 FLOW (data / energy flow) — Flow (ASCII)"),
    ("## §7 VERIFY (Python 검증)", "## §7 VERIFY (Python check)"),
    ("## §6 EVOLVE (Mk.I~V 진화)", "## §6 EVOLVE (Mk.I~V evolution)"),

    # Numbered subheaders and inline labels
    ("### 현 기술이 막혔던 5가지 이유", "### Five reasons current tech stalled"),
    ("### 성능 비교 ASCII 막대 (시중 최고 vs HEXA)",
     "### Performance comparison ASCII bars (market SOTA vs HEXA)"),
    ("### 핵심 돌파구: n=6 완전수 닫힘",
     "### Key breakthrough draft: n=6 perfect-number closure"),
    ("### 5단 체인 시스템맵", "### 5-tier chain system map"),
    ("### n=6 파라미터 완전 매핑", "### n=6 parameter full mapping"),
    ("#### L0 기초 구조", "#### L0 foundation structure"),
    ("#### L1 핵심 채널", "#### L1 core channels"),
    ("#### L2 제어 중복", "#### L2 control redundancy"),
    ("#### L3 통합 대칭", "#### L3 integration symmetry"),
    ("#### L4 응용 보호", "#### L4 application protection"),
    ("### 제원 총괄표", "### Specifications summary"),
    ("### BT 연결", "### BT cross-links"),
    ("### 에너지 플로우", "### Energy flow"),
    ("### 모드별 자원 분배", "### Mode-wise resource distribution"),
    ("### 모드 5개", "### Five modes"),
    ("#### 모드 1: 정규 동작 (Nominal)", "#### Mode 1: Nominal"),
    ("#### 모드 2: 고성능 (High-Perf)", "#### Mode 2: High-Perf"),
    ("#### 모드 3: 전이 (Transition)", "#### Mode 3: Transition"),
    ("#### 모드 4: 오류 복구 (Fault-Tolerant)", "#### Mode 4: Fault-Tolerant"),
    ("#### 모드 5: 보존 (Preservation)", "#### Mode 5: Preservation"),
    ("### DSE 후보군 (5단 × 후보 = 전수 탐색)",
     "### DSE candidate pool (5 tiers x candidates = full sweep)"),
    ("#### Pareto Top-6", "#### Pareto Top-6"),
    ("### Testable Predictions (검증 가능한 예측 10건)",
     "### Testable Predictions (10 testable predictions)"),
    ("### n=6 정직성 검증 10 카테고리",
     "### n=6 honesty check — 10 categories"),
    ("### §7.0 CONSTANTS — 수론 함수 자동 유도",
     "### §7.0 CONSTANTS — number-theoretic auto-derivation"),
    ("### §7.1 DIMENSIONS — SI 단위 일관성",
     "### §7.1 DIMENSIONS — SI unit consistency"),
    ("### §7.2 CROSS — 독립 경로 3개 재유도",
     "### §7.2 CROSS — three independent paths"),
    ("### §7.3 SCALING — log-log 회귀로 지수 역추정",
     "### §7.3 SCALING — exponent via log-log regression"),
    ("### §7.4 SENSITIVITY — ±10% 볼록성",
     "### §7.4 SENSITIVITY — +/-10% convexity"),
    ("### §7.5 LIMITS — 물리 상한 미초과",
     "### §7.5 LIMITS — no breach of physical caps"),
    ("### §7.6 CHI2 — H₀: n=6 우연 가설 p-value",
     "### §7.6 CHI2 — H0: n=6 coincidence p-value"),
    ("### §7.7 OEIS — 외부 시퀀스 DB 매칭",
     "### §7.7 OEIS — external sequence DB match"),
    ("### §7.8 PARETO — Monte Carlo 전수 탐색",
     "### §7.8 PARETO — Monte Carlo full sweep"),
    ("### §7.9 SYMBOLIC — Fraction 정확 유리수 일치",
     "### §7.9 SYMBOLIC — Fraction exact rational equality"),
    ("### §7.10 COUNTER — 반례 + Falsifier",
     "### §7.10 COUNTER — counterexamples + falsifiers"),
    ("### §7 통합 검증 코드 (stdlib only)",
     "### §7 integrated check code (stdlib only)"),

    # TP-n headers (stable across files)
    ("#### TP-1: 자유도 = n = 6 (SE(3) 차원)",
     "#### TP-1: DOF = n = 6 (SE(3) dimension)"),
    ("#### TP-2: 채널 수 = σ(6) = 12",
     "#### TP-2: channel count = sigma(6) = 12"),
    ("#### TP-3: 중복도 = n/φ = 3 (삼중 FBW)",
     "#### TP-3: redundancy = n/phi = 3 (triple FBW)"),
    ("#### TP-4: 접촉수 = K_6 = 12 (kissing number)",
     "#### TP-4: kissing number = K_6 = 12"),
    ("#### TP-5: 처리량 σ² = 144x",
     "#### TP-5: throughput sigma^2 = 144x"),
    ("#### TP-6: 에너지 η → Carnot η = 1 - T_c/T_h",
     "#### TP-6: energy eta -> Carnot eta = 1 - T_c/T_h"),
    ("#### TP-7: B⁴ confinement 지수 = 4.0 ± 0.1",
     "#### TP-7: B^4 confinement exponent = 4.0 +/- 0.1"),
    ("#### TP-8: 화성 τ=4일 (2g 지속 가속)",
     "#### TP-8: Mars tau=4 days (2g sustained accel)"),
    ("#### TP-9: Boltzmann 상태수 = σ = 12",
     "#### TP-9: Boltzmann microstates = sigma = 12"),
    ("#### TP-10: 수명 σ·τ = 48 개월",
     "#### TP-10: lifespan sigma*tau = 48 months"),

    # Long prose blocks (pick unique variants first)
    ("n=6 완전수 산술(σ(6)=12, τ(6)=4, φ(6)=2, sopfr(6)=5)이",
     "n=6 perfect-number arithmetic (sigma(6)=12, tau(6)=4, phi(6)=2, sopfr(6)=5) threads"),
    ("가 어떤 일상 변화를 만드는지 아래 표로 요약한다.",
     " — the table below summarizes the everyday changes this introduces."),
    (" 전 구조를 관통한다.", " across its full structure."),
    ("현재 기술 (", "Current technology ("),
    (") 대비 HEXA 설계 (", ") vs HEXA design ("),

    # Table row labels (§1 effect table)
    ("| 효과 | 현재 | HEXA 이후 | 체감 변화 |",
     "| effect | current | after HEXA | felt change |"),
    ("| 정밀도 | 1.0 단위 | **σ-φ=10배 향상** | 측정 한계 10배 돌파 |",
     "| precision | 1.0 unit | **sigma-phi=10x gain** | measurement limit breaks 10x |"),
    ("| 처리량 | 1.0x | **σ²=144x** | 쓰루풋 2자릿수 증폭 |",
     "| throughput | 1.0x | **sigma^2=144x** | throughput amplified two orders |"),
    ("| 에너지 비용 | 100% | **1/σ=8.3%** | 전력요금 90% 절감 |",
     "| energy cost | 100% | **1/sigma=8.3%** | electricity bill down 90% |"),
    ("| 장비 크기 | 1.0 L | **1/(σ-φ)=0.1 L** | 탁상 장비화 |",
     "| equipment size | 1.0 L | **1/(sigma-phi)=0.1 L** | benchtop equipment |"),
    ("| 오차율 | 1% | **1/σ²=0.7%** | 재현성 2자릿수 개선 |",
     "| error rate | 1% | **1/sigma^2=0.7%** | reproducibility improved two orders |"),
    ("| 학습 속도 | n 주 | **τ=4 일** | 기술 습득 문턱 급락 |",
     "| learning speed | n weeks | **tau=4 days** | skill-acquisition barrier drops |"),
    ("| 수명/신뢰 | 1년 | **σ·τ=48 개월** | 유지보수 부담 최소 |",
     "| life / reliability | 1 year | **sigma*tau=48 months** | maintenance burden minimal |"),
    ("| 접근성 | 전문가 전용 | **n=6명 팀** | 연구실 단위 접근 |",
     "| accessibility | experts only | **n=6 team** | lab-sized access |"),
    ("| 오염/폐기물 | 100% | **≈0%** | R=0 무손실 작동 |",
     "| pollution / waste | 100% | **~=0%** | R=0 lossless operation |"),
    ("| 전문성 문턱 | 박사급 | **학부 σ-τ=8 학기** | 교육 확산 가능 |",
     "| expertise bar | PhD-level | **undergrad sigma-tau=8 semesters** | education reach widens |"),

    ("**한 문장 요약**:", "**One-sentence summary**:"),
    ("### 일상 시나리오", "### Daily scenario"),

    # Daily scenario block
    ("  오전 6:00", "  06:00"),
    ("  오전 σ=12:00  정규 실험 배치 τ=4세트 완료",
     "  sigma=12:00  regular experiment batch tau=4 sets complete"),
    ("  오후 2:00  데이터 σ² 샘플 분석 종료",
     "  14:00  data sigma^2 sample analysis ends"),
    ("  오후 6:00  결과 n=6팀 공유, 다음 가설 도출",
     "  18:00  results shared across n=6 team, next hypothesis drafted"),
    ("  장비 크기: 1/(σ-φ)=0.1 L",
     "  equipment size: 1/(sigma-phi)=0.1 L"),
    ("  오차율:   1/σ²=0.7%", "  error rate:     1/sigma^2=0.7%"),
    ("  소비전력: 기존 1/σ", "  power:          1/sigma of baseline"),
    (" 시스템 기동 (소비전력 1/σ)", " system start (power 1/sigma)"),

    # §2 COMPARE block
    ("│  장벽              │  왜 불가능했나              │  n=6가 어떻게 해결하나      │",
     "│  barrier           │  why infeasible             │  how n=6 addresses it    │"),
    ("│ 1. 파라미터 폭증   │ 자유도 n≫6 → 조합 폭발      │ n=6 완전수 닫힘 σ(6)=12    │",
     "│ 1. param blow-up   │ DOF n>>6 -> combo blow-up   │ n=6 perfect closure sigma(6)=12 │"),
    ("│ 2. 에너지 벽       │ 열역학 2법칙 + 소자 저항    │ R=0 SC + Carnot 접근 한계 │",
     "│ 2. energy wall     │ 2nd law + device resistance │ R=0 SC + Carnot limit     │"),
    ("│ 3. 노이즈 바닥     │ 양자/열 요동 중첩          │ σ=12 평균화 + n=6 필터    │",
     "│ 3. noise floor     │ quantum/thermal jitter mix  │ sigma=12 averaging + n=6 filter │"),
    ("│ 4. 제조 난이도     │ 고유 재료 비싼 공정         │ C Z=6 Diamond 보편성      │",
     "│ 4. fab difficulty  │ rare materials, costly proc │ C Z=6 Diamond universality│"),
    ("│ 5. 스케일링        │ B⁴ / N^3 지수 폭주         │ σ·τ=48T 상한 + n=6 축     │",
     "│ 5. scaling         │ B^4 / N^3 exponential blow  │ sigma*tau=48T cap + n=6 axis │"),

    # Performance bars
    ("│  [핵심 지표] 비교: 현재 기술 vs ",
     "│  [core metric] comparison: current tech vs "),
    ("│  정밀도 (상대)                                                          │",
     "│  precision (relative)                                                   │"),
    ("│  현재 (SOTA)       ██████████░░░░░░░░░░░░░░░░░░░░  1.0x                 │",
     "│  current (SOTA)    ██████████░░░░░░░░░░░░░░░░░░░░  1.0x                 │"),
    ("│  HEXA 설계         ████████████████████████████████  σ-φ=10x            │",
     "│  HEXA design       ████████████████████████████████  sigma-phi=10x      │"),
    ("│  처리량 (쓰루풋)                                                        │",
     "│  throughput                                                             │"),
    ("│  현재              ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1.0x                │",
     "│  current           ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1.0x                │"),
    ("│  HEXA              ████████████████████████████████  σ²=144x            │",
     "│  HEXA              ████████████████████████████████  sigma^2=144x       │"),
    ("│  에너지 비용 (↓)                                                        │",
     "│  energy cost (↓)                                                        │"),
    ("│  현재              ████████████████████████████████  100%               │",
     "│  current           ████████████████████████████████  100%               │"),
    ("│  HEXA              ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1/σ=8.3%           │",
     "│  HEXA              ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1/sigma=8.3%        │"),
    ("│  장비 크기 (↓)                                                          │",
     "│  equipment size (↓)                                                     │"),
    ("│  현재              ████████████████████████████████  1.0 L              │",
     "│  current           ████████████████████████████████  1.0 L              │"),
    ("│  HEXA              █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.1 L (1/(σ-φ))    │",
     "│  HEXA              █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.1 L (1/(sigma-phi))│"),
    ("│  오차율 (↓)                                                             │",
     "│  error rate (↓)                                                         │"),
    ("│  현재              ████████████████████████████████  1% (1/100)         │",
     "│  current           ████████████████████████████████  1% (1/100)         │"),
    ("│  HEXA              █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.7% (1/σ²)        │",
     "│  HEXA              █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.7% (1/sigma^2)    │"),
    ("│  수명/신뢰 (개월)                                                       │",
     "│  life / reliability (months)                                            │"),
    ("│  현재              ██████░░░░░░░░░░░░░░░░░░░░░░░░░  12 개월             │",
     "│  current           ██████░░░░░░░░░░░░░░░░░░░░░░░░░  12 months           │"),
    ("│  HEXA              ████████████████████████████████  σ·τ=48 개월        │",
     "│  HEXA              ████████████████████████████████  sigma*tau=48 months│"),

    # Key breakthrough block
    ("현재 기술의 한계는 **자유도 수**와 **R 무손실** 두 축이 결정한다:",
     "The current-tech ceiling is set by two axes — **DOF count** and **R losslessness**:"),
    ("- 자유도: n=6 = σ(6)/φ(6) = 12/2 = 6 (완전수 자기정합)",
     "- DOF: n=6 = sigma(6)/phi(6) = 12/2 = 6 (perfect-number self-consistency)"),
    ("- 에너지: R=0 SC + Carnot 한계 접근 → η ≤ 1-T_c/T_h",
     "- energy: R=0 SC + Carnot-limit approach -> eta <= 1 - T_c/T_h"),
    ("- 스케일링: σ·τ=48 상한에서 B⁴ confinement 4.0 ± 0.1",
     "- scaling: B^4 confinement 4.0 +/- 0.1 under sigma*tau=48 cap"),
    ("**n=6 완전수가 만드는 연쇄 혁명**:",
     "**Chain cascade induced by the n=6 perfect number**:"),
    ("    → 자유도 SE(3) = R^3 × SO(3) = 6-DOF    ... 공간 제어 최소",
     "    -> DOF SE(3) = R^3 x SO(3) = 6-DOF       ... minimal spatial control"),
    ("      → σ(6) = 12 약수합            ... 12 채널 평균화",
     "      -> sigma(6) = 12 divisor sum ... 12-channel averaging"),
    ("      → τ(6) = 4 약수수              ... τ=4g 가속, τ=4 중복",
     "      -> tau(6) = 4 divisor count  ... tau=4g accel, tau=4 redundancy"),
    ("      → φ(6) = 2 최소소인수          ... 양측 대칭 설계",
     "      -> phi(6) = 2 min prime      ... bilateral symmetry"),
    ("      → sopfr(6) = 5 소인수합        ... sopfr=5단계 보호",
     "      -> sopfr(6) = 5 prime sum    ... sopfr=5 protection tiers"),

    # §3 REQUIRES prose
    ("선행 의존 없음 — 본 도메인 자체로 완결되며 순수 수학/물리 구조에서 n=6 필연성을 유도한다.",
     "No upstream dependency — this domain is self-contained and derives n=6 inevitability from pure math/physics structure."),

    # §4 STRUCT chain diagram
    ("│   L0 기초  │   L1 핵심  │   L2 제어  │   L3 통합  │   L4 응용           │",
     "│  L0 base   │  L1 core   │  L2 ctrl   │  L3 integ  │  L4 apply           │"),
    ("│  n=6 자유도│  σ=12 채널 │  τ=4 중복  │  φ=2 대칭  │  sopfr=5 보호       │",
     "│  n=6 DOF   │  sigma=12 ch│  tau=4 red │  phi=2 sym │  sopfr=5 protect    │"),
    ("│  SE(3)     │  30도 배치 │  FBW/FT    │  좌우/위아래│  5단 G-suit         │",
     "│  SE(3)     │  30deg pitch│  FBW/FT    │  L-R/U-D    │  5-tier G-suit      │"),

    # STRUCT table headers repeated
    ("| 파라미터 | 값 | n=6 수식 | 물리 근거 | 판정 |",
     "| parameter | value | n=6 formula | physics basis | verdict |"),
    # L0 rows
    ("| 자유도 | 6 | n = 6 | SE(3) = R³ × SO(3) (BT-123) | EXACT |",
     "| DOF | 6 | n = 6 | SE(3) = R^3 x SO(3) (BT-123) | EXACT |"),
    ("| 대칭축 | 2 | φ = 2 | 양측 대칭 (BT-124) | EXACT |",
     "| symmetry axes | 2 | phi = 2 | bilateral symmetry (BT-124) | EXACT |"),
    ("| 최소 안정 | 4 | τ = 4 | 이동 최소 안정 (BT-125) | EXACT |",
     "| min stable | 4 | tau = 4 | min translation stability (BT-125) | EXACT |"),
    ("| 약수합 | 12 | σ(6) = 12 | OEIS A000203 | EXACT |",
     "| divisor sum | 12 | sigma(6) = 12 | OEIS A000203 | EXACT |"),
    ("| 약수수 | 4 | τ(6) = 4 | OEIS A000005 | EXACT |",
     "| divisor count | 4 | tau(6) = 4 | OEIS A000005 | EXACT |"),
    ("| 소인수합 | 5 | sopfr(6) = 5 | OEIS A001414 | EXACT |",
     "| prime-factor sum | 5 | sopfr(6) = 5 | OEIS A001414 | EXACT |"),

    # L1 rows
    ("| 채널 수 | 12 | σ = 12 | 30도 간격 전방위 | EXACT |",
     "| channel count | 12 | sigma = 12 | 30-degree full sweep | EXACT |"),
    ("| 배치 간격 | 30도 | 360/σ | σ=12 kissing (BT-127) | EXACT |",
     "| placement gap | 30 deg | 360/sigma | sigma=12 kissing (BT-127) | EXACT |"),
    ("| 게이트 수 | 144 | σ² = 144 | BT-90 GPU SM | EXACT |",
     "| gate count | 144 | sigma^2 = 144 | BT-90 GPU SM | EXACT |"),
    ("| 접촉수 | 12 | K_6 = 12 | BT-49 Kissing | EXACT |",
     "| kissing count | 12 | K_6 = 12 | BT-49 Kissing | EXACT |"),
    ("| J_2 | 24 | 2σ = 24 | 이차형식 최소 벡터 | EXACT |",
     "| J_2 | 24 | 2*sigma = 24 | quadratic-form minimal vector | EXACT |"),
    ("| 코드 거리 | 8 | σ-τ = 8 | Golay [24,12,8] | EXACT |",
     "| code distance | 8 | sigma-tau = 8 | Golay [24,12,8] | EXACT |"),

    # L2 rows
    ("| 중복도 | 3 | n/φ = 3 | 삼중 중복 (BT-276) | EXACT |",
     "| redundancy | 3 | n/phi = 3 | triple redundancy (BT-276) | EXACT |"),
    ("| FBW 수 | 4 | τ = 4 | FBW + FT 독립 | EXACT |",
     "| FBW count | 4 | tau = 4 | FBW + FT independent | EXACT |"),
    ("| 센서 IMU | 6 | n = 6 | 3축 가속+자이로 | EXACT |",
     "| IMU sensors | 6 | n = 6 | 3-axis accel+gyro | EXACT |"),
    ("| 통신 | 12 | σ = 12 | 다중 채널 | EXACT |",
     "| comms | 12 | sigma = 12 | multi-channel | EXACT |"),
    ("| AI 코어 | 144 | σ² = 144 | onboard SM | EXACT |",
     "| AI cores | 144 | sigma^2 = 144 | onboard SM | EXACT |"),
    ("| 지연 | 1 ms | μ(6)=1 | Mobius μ(6)=0 음수 제외 | EXACT |",
     "| latency | 1 ms | mu(6)=1 | Mobius mu(6)=0 negatives excluded | EXACT |"),

    # L3 rows
    ("| 대칭 | 양측 | φ=2 | 좌우 (BT-124) | EXACT |",
     "| symmetry | bilateral | phi=2 | L-R (BT-124) | EXACT |"),
    ("| 결합 | 2쌍 | φ×2 | 상하좌우 | EXACT |",
     "| coupling | 2 pairs | phi*2 | U-D-L-R | EXACT |"),
    ("| 블레이드 | 6 | n = 6 | BT-270 최적 | EXACT |",
     "| blades | 6 | n = 6 | BT-270 optimum | EXACT |"),
    ("| 뷰포트 | 12 | σ = 12 | BT-127 | EXACT |",
     "| viewports | 12 | sigma = 12 | BT-127 | EXACT |"),
    ("| 착륙각 | 3 | n/φ = 3 | 삼각 안정 | EXACT |",
     "| landing angles | 3 | n/phi = 3 | triangular stability | EXACT |"),
    ("| 리벳 | 0 | R(6)-1=0 | 일체 성형 | EXACT |",
     "| rivets | 0 | R(6)-1=0 | monolithic forming | EXACT |"),

    # L4 rows
    ("| G-suit 단계 | 5 | sopfr=5 | 고G 보호 (BT-276) | EXACT |",
     "| G-suit tiers | 5 | sopfr=5 | high-G protection (BT-276) | EXACT |"),
    ("| 레이어 | 5 | sopfr=5 | 차폐 레이어 | EXACT |",
     "| layers | 5 | sopfr=5 | shielding layers | EXACT |"),
    ("| 승무원 | 6 | n = 6 | BT-273 | EXACT |",
     "| crew | 6 | n = 6 | BT-273 | EXACT |"),
    ("| 환경 변수 | 6 | n = 6 | O₂/CO₂/T/P/H₂O/Rad | EXACT |",
     "| env variables | 6 | n = 6 | O2/CO2/T/P/H2O/Rad | EXACT |"),
    ("| 가속 한계 | 4 g | τ=4 | 구조 한계 | EXACT |",
     "| accel cap | 4 g | tau=4 | structural cap | EXACT |"),
    ("| 순항 가속 | 2 g | φ=2 | 쾌적 (BT-283) | EXACT |",
     "| cruise accel | 2 g | phi=2 | comfort (BT-283) | EXACT |"),

    # Specifications table body
    ("│  자유도 (DOF)       n = 6                                                │",
     "│  DOF                n = 6                                                │"),
    ("│  채널 수            σ = 12                                               │",
     "│  channel count      sigma = 12                                           │"),
    ("│  게이트/코어        σ² = 144                                             │",
     "│  gates / cores      sigma^2 = 144                                        │"),
    ("│  중복도             n/φ = 3 (삼중)                                       │",
     "│  redundancy         n/phi = 3 (triple)                                   │"),
    ("│  FBW + FT           τ = 4                                                │",
     "│  FBW + FT           tau = 4                                              │"),
    ("│  대칭축             φ = 2 (양측)                                         │",
     "│  symmetry axes      phi = 2 (bilateral)                                  │"),
    ("│  소인수 보호        sopfr = 5                                            │",
     "│  prime protection   sopfr = 5                                            │"),
    ("│  자장 B (SC)        σ·τ = 48 T                                           │",
     "│  B field (SC)       sigma*tau = 48 T                                     │"),
    ("│  Mach 한계          σ-φ = 10                                             │",
     "│  Mach limit         sigma-phi = 10                                       │"),
    ("│  J_2 최소 벡터      2σ = 24                                              │",
     "│  J_2 min vector     2*sigma = 24                                         │"),
    ("│  Golay 거리         σ-τ = 8                                              │",
     "│  Golay distance     sigma-tau = 8                                        │"),
    ("│  완전수 검증        σ(n) = 2n ✓                                          │",
     "│  perfect-num check  sigma(n) = 2n OK                                     │"),

    # BT table
    ("| BT | 이름 | 적용 |", "| BT | name | use |"),
    ("| BT-123 | SE(3) dim=n=6 | 6-DOF 기본 정리 |",
     "| BT-123 | SE(3) dim=n=6 | 6-DOF base lemma |"),
    ("| BT-124 | φ=2 양측 대칭 | 좌우 대칭 설계 |",
     "| BT-124 | phi=2 bilateral symmetry | L-R symmetric design |"),
    ("| BT-125 | τ=4 이동 안정 | 최소 착륙각 |",
     "| BT-125 | tau=4 translation stability | min landing angle |"),
    ("| BT-127 | σ=12 kissing | 12 채널 커버 |",
     "| BT-127 | sigma=12 kissing | 12-channel cover |"),
    ("| BT-85  | C Z=6 보편 | Diamond 소재 |",
     "| BT-85  | C Z=6 universality | Diamond material |"),
    ("| BT-90  | SM=φ×K₆ | GPU σ²=144 |",
     "| BT-90  | SM=phi*K6 | GPU sigma^2=144 |"),
    ("| BT-276 | 삼중 FBW | n/φ=3 중복 |",
     "| BT-276 | triple FBW | n/phi=3 redundancy |"),
    ("| BT-273 | 승무원 n=6 | Apollo 확장 |",
     "| BT-273 | crew n=6 | Apollo extension |"),
    ("| BT-401 | 양자정보엔진 | BT-543 YM β_0 |",
     "| BT-401 | quantum-info engine | BT-543 YM beta_0 |"),
    ("| BT-404 | Boltzmann | σ=12 엔트로피 |",
     "| BT-404 | Boltzmann | sigma=12 entropy |"),

    # §5 FLOW
    ("│  입력 ──→ [L0 파싱] ──→ [L1 변환] ──→ [L2 제어] ──→ [L3 통합] ──→ 출력    │",
     "│  input --> [L0 parse] --> [L1 xfrm] --> [L2 ctrl] --> [L3 integ] --> out  │"),
    ("│   n=6      n=6 DOF       σ=12 채널    τ=4 중복      φ=2 쌍        결과    │",
     "│   n=6      n=6 DOF       sigma=12 ch  tau=4 red     phi=2 pair    result  │"),
    ("│  R=0        무손실        SC 배선      FBW 보호     대칭 확인      응답   │",
     "│  R=0       lossless      SC wiring    FBW protect  symmetry chk  response │"),
    ("│  상세 플로우:                                                            │",
     "│  detailed flow:                                                          │"),
    ("│  입력 ──→ [n=6 자유도 표준화] ──→ [σ=12 채널 평균] ──→ [τ=4 중복 투표]    │",
     "│  input --> [n=6 DOF normalize] --> [sigma=12 ch avg] --> [tau=4 red vote] │"),
    ("│           n=6 축 정규화          σ=12 멀티플렉스    τ=4 다수결 필터     │",
     "│           n=6 axis normalize     sigma=12 mux         tau=4 majority flt  │"),

    # Mode resource bars
    ("│ Mode 1  │ █████████████████████████░░░░░░  주처리 80% + 통신 20%         │",
     "│ Mode 1  │ █████████████████████████░░░░░░  main 80% + comms 20%          │"),
    ("│ Mode 2  │ ██████████████████████████████░░  주처리 90% + 기타 10%        │",
     "│ Mode 2  │ ██████████████████████████████░░  main 90% + other 10%         │"),
    ("│ Mode 3  │ ███████████████████████████████░  주처리 95% + 기타 5%         │",
     "│ Mode 3  │ ███████████████████████████████░  main 95% + other 5%          │"),
    ("│ Mode 4  │ ██████████████████████████░░░░░░  주처리 80% + 보호 20%        │",
     "│ Mode 4  │ ██████████████████████████░░░░░░  main 80% + protect 20%       │"),
    ("│ Mode 5  │ ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░  주처리 10% + 보호 90%        │",
     "│ Mode 5  │ ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░  main 10% + protect 90%        │"),

    # Mode 1-5 blocks
    ("│  자유도: n = 6 전부 활성                  │",
     "│  DOF: n = 6 all active                   │"),
    ("│  채널: σ = 12 동시                       │",
     "│  channels: sigma = 12 concurrent         │"),
    ("│  중복도: n/φ = 3 투표                    │",
     "│  redundancy: n/phi = 3 vote              │"),
    ("│  소음: 기저 레벨 J_2=24 단위               │",
     "│  noise: baseline J_2=24 units            │"),
    ("│  원리: σ(6)=12 완전수 약수합             │",
     "│  principle: sigma(6)=12 divisor sum      │"),
    ("│  용도: 표준 작동, 반복 실험               │",
     "│  use: standard run, repeat experiment    │"),
    ("│  처리량: σ² = 144x 기준                   │",
     "│  throughput: sigma^2 = 144x baseline     │"),
    ("│  장치: 48T SC 풀로드                      │",
     "│  hardware: 48T SC full load              │"),
    ("│  정밀: σ-φ = 10x 향상                    │",
     "│  precision: sigma-phi = 10x gain         │"),
    ("│  가속: τ = 4 g 한계                      │",
     "│  accel: tau = 4 g cap                    │"),
    ("│  소음: J_2 = 24 단위                     │",
     "│  noise: J_2 = 24 units                   │"),
    ("│  원리: B⁴ confinement 활용                │",
     "│  principle: uses B^4 confinement         │"),
    ("│  상태: 저부하 → 고부하 또는 역            │",
     "│  state: low -> high or reverse           │"),
    ("│  시간: τ = 4 단위 동안                    │",
     "│  duration: tau = 4 units                 │"),
    ("│  원리: 히스테리시스 회피                  │",
     "│  principle: hysteresis avoidance         │"),
    ("│  보호: sopfr=5 단계 릴레이                │",
     "│  protect: sopfr=5 tier relay             │"),
    ("│  가속: φ = 2 g (쾌적)                    │",
     "│  accel: phi = 2 g (comfort)              │"),
    ("│  FBW: τ=4 독립 채널                       │",
     "│  FBW: tau=4 independent channels         │"),
    ("│  투표: n/φ=3 다수결                      │",
     "│  vote: n/phi=3 majority                  │"),
    ("│  거리: σ-τ = 8                           │",
     "│  distance: sigma-tau = 8                 │"),
    ("│  복구: sopfr=5 단계 점진                  │",
     "│  recovery: sopfr=5 tier gradual          │"),
    ("│  상태: 최저 전력, 데이터 보존             │",
     "│  state: lowest power, data preserve      │"),
    ("│  수명: σ·τ = 48 개월                     │",
     "│  life: sigma*tau = 48 months             │"),
    ("│  전력: 1/σ = 8.3% 기저                   │",
     "│  power: 1/sigma = 8.3% baseline          │"),
    ("│  재개: μ(6)=1 ms                         │",
     "│  resume: mu(6)=1 ms                      │"),
    ("│  보호: 48T 자기 차폐                      │",
     "│  protect: 48T magnetic shielding         │"),

    # DSE block
    ("│  L0 기초 │-->│   L1 핵심│-->│  L2 제어 │-->│   L3 통합│-->│ L4 응용  │",
     "│  L0 base │-->│   L1 core│-->│  L2 ctrl │-->│   L3 integ│-->│ L4 apply │"),
    ("전수: 6×5×4×5×4 = 2,400 | 호환 필터: 576 (24%) | Pareto: J_2=24 경로",
     "full: 6x5x4x5x4 = 2,400 | compat filter: 576 (24%) | Pareto: J_2=24 path"),

    # Pareto table
    ("| Rank | L0 | L1 | L2 | L3 | L4 | n6% | 비고 |",
     "| Rank | L0 | L1 | L2 | L3 | L4 | n6% | note |"),
    ("| 1 | n=6 DOF | σ=12 Ch | n/φ=3 FBW | φ=2 대칭 | sopfr=5 보호 | 93% | **최적** |",
     "| 1 | n=6 DOF | sigma=12 Ch | n/phi=3 FBW | phi=2 sym | sopfr=5 protect | 93% | **best** |"),
    ("| 2 | n=6 DOF | σ=12 Ch | τ=4 중복 | φ=2 대칭 | sopfr=5 보호 | 91% | 보수형 |",
     "| 2 | n=6 DOF | sigma=12 Ch | tau=4 red | phi=2 sym | sopfr=5 protect | 91% | conservative |"),
    ("| 3 | n=6 DOF | σ=12 Ch | n/φ=3 FBW | φ=2 대칭 | τ=4 보호 | 88% | 단순화 |",
     "| 3 | n=6 DOF | sigma=12 Ch | n/phi=3 FBW | phi=2 sym | tau=4 protect | 88% | simplified |"),
    ("| 4 | n=6 DOF | sopfr=5 | n/φ=3 FBW | n/φ=3 | sopfr=5 | 90% | 대안 |",
     "| 4 | n=6 DOF | sopfr=5 | n/phi=3 FBW | n/phi=3 | sopfr=5 | 90% | alternative |"),
    ("| 5 | n=6 DOF | σ=12 Ch | τ=4 중복 | φ=2 | τ=4 보호 | 85% | 표준 |",
     "| 5 | n=6 DOF | sigma=12 Ch | tau=4 red | phi=2 | tau=4 protect | 85% | standard |"),
    ("| 6 | τ=4 DOF | σ=12 Ch | n/φ=3 FBW | φ=2 | sopfr=5 | 82% | 축소형 |",
     "| 6 | tau=4 DOF | sigma=12 Ch | n/phi=3 FBW | phi=2 | sopfr=5 | 82% | compact |"),

    # §7 VERIFY prose
    (" 가 물리/수학적으로 성립하는지 stdlib 만으로 검증. 주장된 설계 사양을 기초 물리 공식으로 cross-check.",
     " — check physical/mathematical validity using stdlib only. Cross-check the claimed design spec against baseline physics formulas."),
    ("- **검증**: 기계적 자유도 수 계산 → R³(병진) + SO(3)(회전) = 6",
     "- **check**: count mechanical DOF -> R^3 (trans) + SO(3) (rot) = 6"),
    ("- **예측**: 6 정확 (오차 0)",
     "- **prediction**: 6 exact (error 0)"),
    ("- **Tier**: 1 (수학 정리, 즉시 검증)",
     "- **Tier**: 1 (math lemma, immediate check)"),
    ("- **검증**: 약수합 σ(n) = Σ d | n → σ(6) = 1+2+3+6 = 12",
     "- **check**: divisor sum sigma(n) = Sum_{d|n} d -> sigma(6) = 1+2+3+6 = 12"),
    ("- **예측**: 12 정확 (오차 0)",
     "- **prediction**: 12 exact (error 0)"),
    ("- **Tier**: 1", "- **Tier**: 1"),
    ("- **검증**: 6/2 = 3 (BT-276)",
     "- **check**: 6/2 = 3 (BT-276)"),
    ("- **예측**: 3 정확",
     "- **prediction**: 3 exact"),
    ("- **검증**: 6차원 최적 격자 접촉수 (BT-49, BT-127)",
     "- **check**: 6-dim optimal lattice kissing (BT-49, BT-127)"),
    ("- **예측**: 12 (Musin 2003 증명)",
     "- **prediction**: 12 (Musin 2003 draft)"),
    ("- **Tier**: 2 (격자 탐색 시뮬레이션)",
     "- **Tier**: 2 (lattice search simulation)"),
    ("- **검증**: σ(6)² = 12² = 144 병렬 스루풋",
     "- **check**: sigma(6)^2 = 12^2 = 144 parallel throughput"),
    ("- **예측**: 144 ± 5% (실측 효율 반영)",
     "- **prediction**: 144 +/- 5% (measured-efficiency factor)"),
    ("- **Tier**: 2", "- **Tier**: 2"),
    ("- **검증**: T_h=10^8, T_c=300 → η = 1 - 3×10^-6 ≈ 1",
     "- **check**: T_h=10^8, T_c=300 -> eta = 1 - 3e-6 ~= 1"),
    ("- **예측**: η ≤ 1 근접, 초과 불가",
     "- **prediction**: eta <= 1 bound, no exceedance"),
    ("- **검증**: [10,20,30,40,48] vs 각 b⁴ log-log 회귀",
     "- **check**: [10,20,30,40,48] vs b^4 log-log regression"),
    ("- **예측**: 4.00 ± 0.05",
     "- **prediction**: 4.00 +/- 0.05"),
    ("- **검증**: t = 2√(d/a) = 2√(5.5×10^10/19.6) ≈ τ일",
     "- **check**: t = 2 sqrt(d/a) = 2 sqrt(5.5e10/19.6) ~= tau days"),
    ("- **예측**: 3.88 ± 0.1 일 ≈ τ=4",
     "- **prediction**: 3.88 +/- 0.1 days ~= tau=4"),
    ("- **검증**: S = k ln(Ω) → Ω = σ(6) = 12 (자유도 약수합)",
     "- **check**: S = k ln(Omega) -> Omega = sigma(6) = 12 (DOF divisor sum)"),
    ("- **예측**: Ω = 12", "- **prediction**: Omega = 12"),
    ("- **검증**: SC R=0 무손실 + C Z=6 방사선 내성",
     "- **check**: SC R=0 lossless + C Z=6 radiation tolerance"),
    ("- **예측**: 48 ± 4 개월 (10% 오차)",
     "- **prediction**: 48 +/- 4 months (10% tolerance)"),
    ("- **Tier**: 3 (수명 시험 필요)",
     "- **Tier**: 3 (lifetime test required)"),
    ("- **Tier**: 1 (수학 정리, 즉시 검증)",
     "- **Tier**: 1 (math lemma, immediate check)"),

    # §7.0 body (physics-specific)
    ("`sigma(6)=12`, `tau(6)=4`, `phi=2`, `sopfr(6)=5`, `J_2=2σ=24`. 하드코딩 0 — OEIS A000203/A000005/A001414 에서 직접 계산. `assert σ(n)==2n` 으로 완전수 성질 자기검증. BT-543 YM β_0, BT-544 NS 3중 공명, BT-546 BSD Sel_6, Hodge (p,q)",
     "`sigma(6)=12`, `tau(6)=4`, `phi=2`, `sopfr(6)=5`, `J_2=2*sigma=24`. Zero hard-coding — computed directly from OEIS A000203/A000005/A001414. `assert sigma(n)==2n` self-checks the perfect-number property. BT-543 YM beta_0, BT-544 NS triple resonance, BT-546 BSD Sel_6, Hodge (p,q)."),
    ("차원 튜플 `(M, L, T, I)` 추적. `F = J·B·V` 는 `[A/m²][T][m³] = [N]` 자동 검증. 차원 불일치 공식은 reject.",
     "Tracks the dim tuple `(M, L, T, I)`. `F = J*B*V` auto-checks `[A/m^2][T][m^3] = [N]`. Dimension mismatches are rejected."),
    ("핵심 수치를 3가지 독립 경로로 재유도. 15% 이내 일치해야 신뢰.",
     "Re-derives the core number along three independent paths. Confidence requires agreement within 15%."),
    ("`B⁴ confinement` 지수가 정말 4인가? 데이터 `[10,20,30,40,48]` vs `b⁴` 로 log 기울기 측정 → 4.0 ± 0.1 확인.",
     "Is the `B^4 confinement` exponent really 4? Measure log-log slope of `[10,20,30,40,48]` vs `b^4` -> confirm 4.0 +/- 0.1."),
    ("`f(n=6)` 에서 n 을 ±10% 흔들어 `f(6.6)` `f(5.4)` 둘 다 `f(6)` 보다 나쁜지 확인. 볼록 극값 = 진짜 최적점, flat = 끼워맞춤.",
     "Perturb n by +/-10% at `f(n=6)` and confirm both `f(6.6)` and `f(5.4)` are worse than `f(6)`. Convex extremum = genuine optimum, flat = fit."),
    ("Carnot `η ≤ 1 - T_c/T_h`, Lawson D-T `n·τ·T ≥ 3×10²¹`. Clay 7난제, 부분 결과 정리, n=6 모듈러 뼈대. claim 이 근본 한계 초과면 reject.",
     "Carnot `eta <= 1 - T_c/T_h`, Lawson D-T `n*tau*T >= 3e21`. Clay 7 problems — partial results — n=6 modular scaffold. Reject any claim that exceeds fundamental caps."),
    ("28 파라미터 예측 vs 관측 χ² 계산 → `erfc(√(χ²/2df))` 로 p-value 근사. p > 0.05 면 n=6 우연 가설 기각 불가 (유의).",
     "Compute chi^2 over 28 parameter predictions vs observations -> approximate p-value via `erfc(sqrt(chi^2/(2*df)))`. p > 0.05 leaves the n=6-coincidence hypothesis non-rejected (significant)."),
    ("`[1,2,3,6,12,24,48]` 이 OEIS 에 등록됨. A000203(sigma), A000005(tau), A000010(phi Euler), A001414(sopfr) 네 개 시퀀스 모두 일치해야 신뢰.",
     "`[1,2,3,6,12,24,48]` registered in OEIS. Confidence requires agreement on all four sequences: A000203 (sigma), A000005 (tau), A000010 (Euler phi), A001414 (sopfr)."),
    ("DSE `K1×K2×K3×K4×K5 = 6×5×4×5×4 = 2400` 조합 샘플링. n=6 구성이 상위 5% 이내인지 통계적 유의성 확인.",
     "Sample DSE `K1*K2*K3*K4*K5 = 6*5*4*5*4 = 2400` combinations. Check statistical significance that the n=6 configuration sits in the top 5%."),
    ("`from fractions import Fraction`. `n/phi = Fraction(6,2) == Fraction(3)` 부동소수 근사가 아닌 정확 유리수 `==` 등호 비교.",
     "`from fractions import Fraction`. `n/phi = Fraction(6,2) == Fraction(3)` — exact rational `==` equality rather than float approximation."),
    ("- 반례 (n=6 무관): 기본전하 e, Planck h, π, 미세구조상수 α — 이들은 n=6 유도 불가, 솔직히 인정",
     "- counterexamples (n=6 unrelated): elementary charge e, Planck h, pi, fine-structure constant alpha — n=6 derivation fails here, acknowledged openly"),
    ("- Falsifier: σ(n) != 12 / τ(n) != 4 / B⁴ 지수 != 4.0 ± 0.1 / Carnot η > 1",
     "- Falsifier: sigma(n) != 12 / tau(n) != 4 / B^4 exponent != 4.0 +/- 0.1 / Carnot eta > 1"),

    # Python VERIFY block comments
    ("# §7 VERIFY — ",
     "# sec7 VERIFY - "),
    (" n=6 정직성 검증 (stdlib only, ",
     " n=6 honesty check (stdlib only, "),
    ("# 10 섹션 구조:",
     "# 10 subsection layout:"),
    ("#   §7.0 CONSTANTS  — n=6 상수를 수론 함수에서 자동 유도 (하드코딩 0)",
     "#   sec7.0 CONSTANTS   - n=6 constants auto-derived from number-theoretic funcs (zero hard-coding)"),
    ("#   §7.1 DIMENSIONS — SI 단위 일관성",
     "#   sec7.1 DIMENSIONS  - SI unit consistency"),
    ("#   §7.2 CROSS      — 같은 결과를 독립 경로 ≥3 으로 재유도",
     "#   sec7.2 CROSS       - same result re-derived on >=3 independent paths"),
    ("#   §7.3 SCALING    — log-log 회귀로 B⁴ 지수 역추정",
     "#   sec7.3 SCALING     - B^4 exponent via log-log regression"),
    ("#   §7.4 SENSITIVITY— n=6 ±10% 흔들어 볼록 극값 확인",
     "#   sec7.4 SENSITIVITY - perturb n=6 +/-10% to confirm convex extremum"),
    ("#   §7.5 LIMITS     — Carnot/Lawson 물리 상한 미초과",
     "#   sec7.5 LIMITS      - no breach of Carnot/Lawson caps"),
    ("#   §7.6 CHI2       — H₀: n=6 우연 가설 p-value 계산",
     "#   sec7.6 CHI2        - H0: n=6 coincidence p-value"),
    ("#   §7.7 OEIS       — n=6 family 시퀀스 외부 DB (A-id) 매칭",
     "#   sec7.7 OEIS        - n=6 family sequences match external DB (A-id)"),
    ("#   §7.8 PARETO     — Monte Carlo 2400 조합 중 n=6 순위",
     "#   sec7.8 PARETO      - n=6 rank among 2400 Monte Carlo combinations"),
    ("#   §7.9 SYMBOLIC   — Fraction 정확 유리수 등호 일치",
     "#   sec7.9 SYMBOLIC    - exact rational equality via Fraction"),
    ("#   §7.10 COUNTER   — 반례 + falsifier 명시 (정직성)",
     "#   sec7.10 COUNTER    - counterexamples + falsifiers (honesty)"),
    ("# 수론 유래 주석 1: σ(6)=12 약수합 — OEIS A000203 직접 계산, 하드코딩 0",
     "# number-theory note 1: sigma(6)=12 divisor sum - OEIS A000203 direct compute, zero hard-coding"),
    ("# 수론 유래 주석 2: τ(6)=4 약수수 — OEIS A000005, 완전수 정체성 자기검증",
     "# number-theory note 2: tau(6)=4 divisor count - OEIS A000005, perfect-number identity self-check"),
    ("# 수론 유래 주석 3: sopfr(6)=5 소인수합 — OEIS A001414, 보호 단계와 정렬",
     "# number-theory note 3: sopfr(6)=5 prime-factor sum - OEIS A001414, aligned with protection tiers"),
    ("# 양자 맞춤 (BT-401~408): BT-543 YM β_0, BT-544 NS 3중 공명, BT-546 BSD Sel_6, Hodge (p,q)",
     "# quantum alignment (BT-401~408): BT-543 YM beta_0, BT-544 NS triple resonance, BT-546 BSD Sel_6, Hodge (p,q)"),
    ("# ─── §7.0 CONSTANTS — n=6 상수를 수론 함수에서 자동 유도 ──────────────────────",
     "# --- sec7.0 CONSTANTS - n=6 constants auto-derived from number-theoretic funcs -----"),
    ("# 수론 유래 1: \"σ=12 는 어디서?\" — 약수의 합 σ(n) = Σ_{d|n} d. n=6 → {1,2,3,6} → 12",
     "# note 1: \"where does sigma=12 come from?\" - divisor sum sigma(n) = Sum_{d|n} d. n=6 -> {1,2,3,6} -> 12"),
    ("# 자기검증: 6 이 \"완전수\" (σ(n)=2n) 이기 때문에 필연적 상수군.",
     "# self-check: 6 is a \"perfect number\" (sigma(n)=2n), so the constants are inevitable."),
    ('    """약수 집합. n=6 → {1,2,3,6}"""',
     '    """Divisor set. n=6 -> {1,2,3,6}"""'),
    ('    """약수의 합 (OEIS A000203). σ(6) = 1+2+3+6 = 12"""',
     '    """Divisor sum (OEIS A000203). sigma(6) = 1+2+3+6 = 12"""'),
    ('    """약수의 개수 (OEIS A000005). τ(6) = |{1,2,3,6}| = 4"""',
     '    """Divisor count (OEIS A000005). tau(6) = |{1,2,3,6}| = 4"""'),
    ('    """소인수의 합 (OEIS A001414). sopfr(6) = 2+3 = 5"""',
     '    """Prime-factor sum (OEIS A001414). sopfr(6) = 2+3 = 5"""'),
    ('    """최소 소인수. φ(6) = 2"""',
     '    """Minimum prime factor. phi(6) = 2"""'),
    ('    """오일러 피 함수 (OEIS A000010). φ_E(6) = |{1,5}| = 2"""',
     '    """Euler phi (OEIS A000010). phi_E(6) = |{1,5}| = 2"""'),
    ("# 수론 유래 2: n=6 family — 모두 수론 함수로 유도, 하드코딩 0",
     "# note 2: n=6 family - all derived from number-theoretic funcs, zero hard-coding"),
    ("# σ(6)·φ_E(6) = 12·2 = 24 ≟ 6·τ(6) = 6·4 = 24 ✓  (n=6 유일성 정리)",
     "# sigma(6)*phi_E(6) = 12*2 = 24 =? 6*tau(6) = 6*4 = 24 OK  (n=6 uniqueness lemma)"),
    ("# 12 = σ(6)", "# 12 = sigma(6)"),
    ("# 4  = τ(6)", "# 4  = tau(6)"),
    ("# 5  = 2+3", "# 5  = 2+3"),
    ("# 24 = 2σ        (← 이차형식 최소 벡터 수)",
     "# 24 = 2*sigma (quadratic-form minimal-vector count)"),
    ("# 10 = σ-φ       (Mach 한계 등)",
     "# 10 = sigma-phi (Mach cap etc.)"),
    ("# 48 = σ·τ       (SC 자장 T)",
     "# 48 = sigma*tau (SC B field T)"),
    ("# 2  = φ_E(6)    (오일러 totient)",
     "# 2  = phi_E(6)  (Euler totient)"),
    ("# 수론 유래 3: n=6 완전수 정체성 — σ(n)=2n 성립해야 (Euclid-Euler 정리)",
     "# note 3: n=6 perfect-number identity - must satisfy sigma(n)=2n (Euclid-Euler)"),
    ('assert SIGMA == 2 * N, "n=6 완전수 성질 위배"',
     'assert SIGMA == 2 * N, "n=6 perfect-number property violated"'),
    ("# σ(6)·φ_E(6) = n·τ(6) 유일성 (pure-mathematics.md 3개 독립증명)",
     "# sigma(6)*phi_E(6) = n*tau(6) uniqueness (pure-mathematics.md, three independent drafts)"),
    ('assert SIGMA * EULER_PHI == N * TAU, "n=6 σφ=nτ 유일성 위배"',
     'assert SIGMA * EULER_PHI == N * TAU, "n=6 sigma*phi=n*tau uniqueness violated"'),
    ("# ─── §7.1 DIMENSIONS — 차원해석 (SI 단위 일관성) ──────────────────────────────",
     "# --- sec7.1 DIMENSIONS - dimensional analysis (SI unit consistency) -----"),
    ("# ─── §7.2 CROSS — 동일 결과 독립 경로 3개로 재유도 ─────────────────────────────",
     "# --- sec7.2 CROSS - same result via 3 independent paths -----"),
    ('    """차원 곱: J*B*V → F"""',
     '    """Dimension product: J*B*V -> F"""'),
    ('    """σ(6)=12 를 3가지 독립 경로로 계산"""',
     '    """Compute sigma(6)=12 along 3 independent paths"""'),
    ("    # 경로 1: 약수 직접 합",
     "    # path 1: direct divisor sum"),
    ("    # 경로 2: 완전수 공식 σ(n)=2n",
     "    # path 2: perfect-number formula sigma(n)=2n"),
    ("    # 경로 3: σ(p·q) = (1+p)(1+q) for p,q 소수 (6=2·3)",
     "    # path 3: sigma(p*q) = (1+p)(1+q) for p,q prime (6=2*3)"),
    ("# ─── §7.3 SCALING — 스케일링 법칙 로그 회귀 ─────────────────────────────────",
     "# --- sec7.3 SCALING - scaling-law log regression -----"),
    ('    """log-log 기울기 = 스케일링 지수"""',
     '    """log-log slope = scaling exponent"""'),
    ("# ─── §7.4 SENSITIVITY — ±10% 흔들어 볼록성 확인 ──────────────────────────────",
     "# --- sec7.4 SENSITIVITY - perturb +/-10% to confirm convexity -----"),
    ('    """f(x0±10%) 둘 다 f(x0) 보다 나빠야 볼록 극값"""',
     '    """both f(x0 +/- 10%) must be worse than f(x0) for a convex extremum"""'),
    ("# ─── §7.5 LIMITS — 물리 상한 미초과 ─────────────────────────────────────────",
     "# --- sec7.5 LIMITS - no breach of physical caps -----"),
    ('    """카르노 효율"""',
     '    """Carnot efficiency"""'),
    ('    """D-T 점화 조건"""',
     '    """D-T ignition condition"""'),
    ("# ─── §7.6 CHI2 — H₀: n=6 우연 가설 p-value ──────────────────────────────────",
     "# --- sec7.6 CHI2 - H0: n=6 coincidence p-value -----"),
    ('    """χ² = Σ(O-E)²/E. p-value 는 erfc 로 근사"""',
     '    """chi^2 = Sum (O-E)^2 / E. p-value approximated via erfc"""'),
    ("# ─── §7.7 OEIS — 외부 시퀀스 DB 매칭 (offline hash) ─────────────────────────",
     "# --- sec7.7 OEIS - external sequence DB match (offline hash) -----"),
    ("# ─── §7.8 PARETO — Monte Carlo 전수 탐색 ────────────────────────────────────",
     "# --- sec7.8 PARETO - Monte Carlo full sweep -----"),
    ('    """K1=n × K2=sopfr × K3=τ × K4=sopfr × K5=τ = 6×5×4×5×4 = 2400"""',
     '    """K1=n x K2=sopfr x K3=tau x K4=sopfr x K5=tau = 6x5x4x5x4 = 2400"""'),
    ("# ─── §7.9 SYMBOLIC — Fraction 으로 정확 유리수 일치 ────────────────────────",
     "# --- sec7.9 SYMBOLIC - exact rational equality via Fraction -----"),
    ("# 6/2 = 3", "# 6/2 = 3"),
    ("# 12/6 = 2 (perfect)", "# 12/6 = 2 (perfect)"),
    ("# 24/6 = 4 = τ", "# 24/6 = 4 = tau"),
    ("# ─── §7.10 COUNTER — 반례/Falsifier (정직성 필수) ──────────────────────────",
     "# --- sec7.10 COUNTER - counterexamples / falsifiers (honesty required) -----"),
    ('    ("기본전하 e = 1.602×10⁻¹⁹ C", "n=6 과 무관 — QED 독립 상수"),',
     '    ("elementary charge e = 1.602e-19 C", "unrelated to n=6 - independent QED constant"),'),
    ('    ("Planck h = 6.626×10⁻³⁴",     "6.6 는 우연, n=6 유도 아님"),',
     '    ("Planck h = 6.626e-34",       "6.6 is coincidence, not n=6-derived"),'),
    ('    ("π = 3.14159...",              "원주율은 기하 상수, n=6 독립"),',
     '    ("pi = 3.14159...",             "geometric constant, n=6-independent"),'),
    ('    ("미세구조상수 α ≈ 1/137",      "137 는 n=6 계열 아님"),',
     '    ("fine-structure alpha ~= 1/137","137 not part of the n=6 family"),'),
    ('    "σ(n) 측정값 != 12 이면 완전수 정체성 붕괴",',
     '    "if sigma(n) measured != 12 the perfect-number identity collapses",'),
    ('    "τ(n) 측정값 != 4 이면 약수수 이론 폐기",',
     '    "if tau(n) measured != 4 the divisor-count theory is discarded",'),
    ('    "B⁴ confinement 지수 측정 != 4.0 ± 0.1 이면 스케일링 폐기",',
     '    "if B^4 confinement exponent measured != 4.0 +/- 0.1 the scaling is discarded",'),
    ('    "Carnot η > 1 이면 열역학 2법칙 붕괴 (reject)",',
     '    "Carnot eta > 1 would collapse the 2nd law (reject)",'),
    ("# ─── 메인 실행 + 집계 ────────────────────────────────────────────────────────",
     "# --- main run + aggregate -----"),
    ("    # §7.0 상수 수론 유도", "    # sec7.0 constants from number-theory"),
    ('    r.append(("§7.0 CONSTANTS 수론 유도",',
     '    r.append(("sec7.0 CONSTANTS number-theory",'),
    ("    # §7.1 차원 일치 F=J·B·V", "    # sec7.1 dim match F=J*B*V"),
    ('    r.append(("§7.1 DIMENSIONS F=J·B·V",',
     '    r.append(("sec7.1 DIMENSIONS F=J*B*V",'),
    ("    # §7.2 3경로 일치", "    # sec7.2 3-path match"),
    ('    r.append(("§7.2 CROSS σ(6) 3경로 일치",',
     '    r.append(("sec7.2 CROSS sigma(6) 3-path match",'),
    ("    # §7.3 B⁴ 지수 ≈ 4.0", "    # sec7.3 B^4 exponent ~= 4.0"),
    ('    r.append(("§7.3 SCALING B⁴ 지수 ≈ 4",',
     '    r.append(("sec7.3 SCALING B^4 exponent ~= 4",'),
    ("    # §7.4 n=6 볼록 최적", "    # sec7.4 n=6 convex optimum"),
    ('    r.append(("§7.4 SENSITIVITY n=6 볼록", convex))',
     '    r.append(("sec7.4 SENSITIVITY n=6 convex", convex))'),
    ("    # §7.5 물리 상한", "    # sec7.5 physical caps"),
    ('    r.append(("§7.5 LIMITS Carnot η < 1", carnot(1e8, 300) < 1.0))',
     '    r.append(("sec7.5 LIMITS Carnot eta < 1", carnot(1e8, 300) < 1.0))'),
    ('    r.append(("§7.5 LIMITS Lawson D-T 점화", lawson_DT(1e20, 1.0, 30)))',
     '    r.append(("sec7.5 LIMITS Lawson D-T ignition", lawson_DT(1e20, 1.0, 30)))'),
    ("    # §7.6 χ² p-value > 0.05", "    # sec7.6 chi^2 p-value > 0.05"),
    ('    r.append(("§7.6 CHI2 H₀ 기각 안 됨", p > 0.05 or chi2 == 0))',
     '    r.append(("sec7.6 CHI2 H0 not rejected", p > 0.05 or chi2 == 0))'),
    ("    # §7.7 OEIS 등록", "    # sec7.7 OEIS registered"),
    ('    r.append(("§7.7 OEIS 시퀀스 등록",',
     '    r.append(("sec7.7 OEIS sequence registered",'),
    ("    # §7.8 Pareto 상위 5%", "    # sec7.8 Pareto top 5%"),
    ('    r.append(("§7.8 PARETO n=6 상위 5%", pareto_rank_n6() < 0.05))',
     '    r.append(("sec7.8 PARETO n=6 top 5%", pareto_rank_n6() < 0.05))'),
    ("    # §7.9 Fraction 정확 일치", "    # sec7.9 Fraction exact match"),
    ('    r.append(("§7.9 SYMBOLIC Fraction 일치",',
     '    r.append(("sec7.9 SYMBOLIC Fraction match",'),
    ("    # §7.10 반례/Falsifier 존재", "    # sec7.10 counter/falsifier present"),
    ('    r.append(("§7.10 COUNTER+FALSIFIERS 명시",',
     '    r.append(("sec7.10 COUNTER+FALSIFIERS listed",'),
    ('    print(f"{passed}/{total} PASS (n=6 정직성 검증)")',
     '    print(f"{passed}/{total} PASS (n=6 honesty check)")'),

    # §6 EVOLVE
    (" 실제 기술 실현 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구:",
     " — technology-realization roadmap. Each Mk tier requires upstream-domain maturity:"),
    ("<summary><b>Mk.V — 2050+ 최종 형태 (current target)</b></summary>",
     "<summary><b>Mk.V — 2050+ final target form (current target)</b></summary>"),
    ("완전 통합 ", "Fully integrated "),
    (" Mk.V. σ=12 채널 × n/φ=3 중복 × sopfr=5 보호 완성.",
     " Mk.V. sigma=12 channels x n/phi=3 redundancy x sopfr=5 protection draft."),
    ("선행 조건: 전 선행 도메인 🛸10 도달.",
     "Prerequisite: all upstream domains reach 10."),
    ("<summary>Mk.IV — 2045~2050 대량 보급</summary>",
     "<summary>Mk.IV — 2045~2050 mass deployment</summary>"),
    ("생산 스케일 σ²=144x. 상용 배포, 교육 표준화 τ=4 단계 완성.",
     "Production scale sigma^2=144x. Commercial deployment, tau=4-tier education standardization draft."),
    ("<summary>Mk.III — 2040~2045 통합 프로토타입</summary>",
     "<summary>Mk.III — 2040~2045 integrated prototype</summary>"),
    ("L0~L4 5단 통합. n=6 EXACT 93% 이상 검증. 유인/상용 인증.",
     "L0~L4 5-tier integration. n=6 EXACT >= 93% checked. Crewed/commercial certification."),
    ("<summary>Mk.II — 2035~2040 부품 수준 연동</summary>",
     "<summary>Mk.II — 2035~2040 component-level integration</summary>"),
    ("개별 서브시스템 통합 테스트 베드. σ·J_2=288 단위 실험.",
     "Per-subsystem integration test-bed. sigma*J_2=288-unit experiment."),
    ("<summary>Mk.I — 2030~2035 소재/부품 단계</summary>",
     "<summary>Mk.I — 2030~2035 materials/components phase</summary>"),
    ("기본 소재 (C Z=6 Diamond) + SC 48T 자석 + n=6 DOF 제어기 모듈.",
     "Base materials (C Z=6 Diamond) + SC 48T magnet + n=6 DOF controller module."),
    ("스케일 모델 τ=4 단위. 부품 단계 — 통합은 Mk.II 이후.",
     "Scale model tau=4 units. Component phase — integration lands in Mk.II."),

    # Misc inline text
    (" 시스템 구조  ", " system architecture "),
    (" 제원  ", " specifications "),

    # §X BLOWUP common skeleton
    ("### §X 돌파 요약", "### §X breakthrough-draft summary"),
    ("### §X.5 검증 가능 falsifier", "### §X.5 testable falsifier"),
    ("### §X.4 검증 가능 falsifier", "### §X.4 testable falsifier"),
    ("### §X.5 alien_index 갱신", "### §X.5 alien_index update"),
    ("### §X.6 atlas 상수 출력 (7건)", "### §X.6 atlas constants output (7 items)"),
    ("**SMASH 요약 (5건)**:", "**SMASH summary (5 items)**:"),
    ("**SMASH 요약 (4건)**:", "**SMASH summary (4 items)**:"),
    ("| # | 돌파 | n=6 공식 | 값 |",
     "| # | breakthrough | n=6 formula | value |"),
    ("| # | 돌파 | n=6 공식 | 값/관계 |",
     "| # | breakthrough | n=6 formula | value / relation |"),
    ("| # | 예측 | n=6 근거 | Falsifier |",
     "| # | prediction | n=6 basis | Falsifier |"),
    ("- **판정**: EXACT [10]", "- **verdict**: EXACT [10]"),
    ("| 판정 |", "| verdict |"),

    # Recurrent §7 verify additions
    ("하드코딩 0 — OEIS A000203/A000005/A001414 에서 직접 계산.",
     "Zero hard-coding - computed directly from OEIS A000203/A000005/A001414."),
    ("`assert σ(n)==2n` 으로 완전수 성질 자기검증.",
     "`assert sigma(n)==2n` self-checks the perfect-number property."),
    ("claim 이 근본 한계 초과면 reject.",
     "Reject any claim that exceeds fundamental caps."),
    ("# 양자 맞춤 (BT-401~408):",
     "# quantum alignment (BT-401~408):"),
    ("양자정보엔진", "quantum-info engine"),

    # Recurring table descriptors that vary per file
    ("ΛCDM n=6 파라미터", "LambdaCDM n=6 parameters"),
    ("Boltzmann n=6 엔트로피", "Boltzmann n=6 entropy"),
    ("n=6 파라미터", "n=6 parameters"),
    ("유일성 정리", "uniqueness lemma"),
    ("완전성", "completeness"),
    ("수론 함수", "number-theoretic functions"),
    ("블랙홀 엔트로피", "black-hole entropy"),
    ("블랙홀 슈바르츠실트", "black-hole Schwarzschild"),
    ("딥필드", "deep field"),
    ("파라미터 확장", "parameter extension"),
    ("우연 가설", "coincidence hypothesis"),
    ("파라미터 예측 vs 관측", "parameter prediction vs observation"),

    # Common Korean particles that appear in tables
    ("합=", "sum="),
    ("주기", "period"),
    ("힉스", "Higgs"),
    ("암흑물질", "dark matter"),
    ("암흑에너지", "dark energy"),
    ("우주", "universe"),
    ("관통", "threads"),
    ("닫힘", "closure"),
    ("확장", "extension"),
    ("정리", "lemma"),
    ("재유도", "re-derivation"),
    ("쌍대", "dual"),
    ("대칭", "symmetry"),
    ("곡률", "curvature"),
    ("진공", "vacuum"),
    ("운동", "motion"),
    ("공간", "space"),
    ("보정", "correction"),
    ("응축", "condensate"),
    ("결합", "coupling"),
    ("세대", "generation"),
    ("표준모형", "Standard Model"),
    ("정규화", "normalization"),
    ("고정점", "fixed point"),
    ("유일성", "uniqueness"),
    ("측정값", "measurement value"),
    ("최소 소인수", "minimum prime factor"),
    ("완전수", "perfect number"),
    ("소인수합", "sum of prime factors"),
    ("소인수", "prime factor"),
    ("약수합", "divisor sum"),
    ("약수수", "divisor count"),
    ("약수", "divisor"),
    ("자유도", "DOF"),
    ("차원", "dimension"),
    ("지수", "exponent"),
    ("계수", "coefficient"),
    ("분모", "denominator"),
    ("분자", "numerator"),
    ("재사용", "reuse"),
    ("엔진", "engine"),
    ("목적", "purpose"),
    ("규칙", "rule"),
    ("중복 금지", "no duplication"),
    ("목표", "target"),
    ("스케일링", "scaling"),
    ("섹터", "sector"),
    ("통합", "integration"),
    ("별개 모델", "separate models"),
    ("통합 스칼라", "integrated scalar"),
    ("묶음", "bundle"),
    ("기존", "existing"),
    ("승격", "promotion"),
    ("본 증명", "main draft"),
    ("본문 기준 적용", "body-text basis applied"),
    ("난제", "problem"),
    ("부분 결과", "partial results"),
    ("모듈러 뼈대", "modular skeleton"),
    ("폐형", "closed form"),
    ("시뮬레이터 프로토콜", "simulator protocol"),

    # Common physics/math vocabulary (single-word / short-phrase)
    ("에서 직접 계산", "computed directly from"),
    ("에서 직접", "directly from"),
    ("에서", "from"),
    ("돌파 요약", "breakthrough-draft summary"),
    ("돌파", "breakthrough-draft"),
    ("폐기", "discarded"),
    ("잠금", "lock"),
    ("합성", "composite"),
    ("삼중", "triple"),
    ("경계 준수", "boundary compliance"),
    ("경계 조건", "boundary condition"),
    ("경계", "boundary"),
    ("불변량", "invariant"),
    ("상한", "upper bound"),
    ("측정", "measurement"),
    ("독립", "independent"),
    ("최소해능", "minimum-resolution"),
    ("최소해", "minimum solution"),
    ("최소기", "minimum term"),
    ("최소", "minimum"),
    ("경로", "path"),
    ("봉합", "sealing"),
    ("상수", "constant"),
    ("증명", "draft"),
    ("정확히", "exactly"),
    ("자기검증", "self-check"),
    ("자기", "self"),
    ("완전", "complete"),
    ("격자", "lattice"),
    ("양자", "quantum"),
    ("임계", "critical"),
    ("복소", "complex"),
    ("핵심", "core"),
    ("산술", "arithmetic"),
    ("인용", "citation"),
    ("중간", "intermediate"),
    ("엔트로피", "entropy"),
    ("공통", "shared"),
    ("유도", "derivation"),
    ("구조", "structure"),
    ("근사", "approximation"),
    ("매개변수", "parameter"),
    ("조합", "combination"),
    ("일치", "match"),
    ("검증", "check"),
    ("영점", "zero"),
    ("에너지", "energy"),
    ("이중", "double"),
    ("직접", "direct"),
    ("분해", "decomposition"),
    ("변환", "transform"),
    ("극값", "extremum"),
    ("체인", "chain"),
    ("수학", "math"),
    ("통일", "unified"),
    ("열역학", "thermodynamics"),
    ("우선", "first"),
    ("가속", "acceleration"),
    ("저항", "resistance"),
    ("요동", "fluctuation"),
    ("소자", "device"),
    ("노이즈", "noise"),
    ("바닥", "floor"),
    ("평균화", "averaging"),
    ("필터", "filter"),
    ("비싼", "expensive"),
    ("공정", "process"),
    ("재료", "material"),
    ("제조", "fabrication"),
    ("난이도", "difficulty"),
    ("자장", "field"),
    ("회귀", "regression"),
    ("주장", "claim"),
    ("주장된", "claimed"),
    ("부합", "alignment"),
    ("연쇄", "chain"),
    ("혁명", "revolution"),
    ("드라이브", "drive"),
    ("코어", "core"),
    ("정렬", "alignment"),
    ("일반", "general"),
    ("형식", "form"),
    ("형식화", "formalization"),
    ("배치", "placement"),
    ("간격", "spacing"),
    ("조건", "condition"),
    ("표기", "notation"),
    ("동명", "same-name"),
    ("체계", "system"),
    ("세 가지", "three"),
    ("다섯 가지", "five"),
    ("파라미터", "parameter"),
    ("파라미터가", "parameters"),
    ("파라미터의", "parameter's"),
    ("기울기", "slope"),
    ("절편", "intercept"),
    ("연산", "operation"),
    ("행렬", "matrix"),
    ("텐서", "tensor"),
    ("벡터", "vector"),
    ("스칼라", "scalar"),
    ("스핀", "spin"),
    ("대응", "correspondence"),
    ("차원이", "dimension"),
    ("정의", "definition"),
    ("총합", "total sum"),
    ("단조증가", "monotone increase"),
    ("단조성", "monotonicity"),
    ("증가", "increase"),
    ("감소", "decrease"),
    ("점진", "gradual"),
    ("비율", "ratio"),
    ("표현", "representation"),
    ("열린", "open"),
    ("닫힌", "closed"),
    ("양정치", "positive-definite"),
    ("랜덤", "random"),
    ("임의", "arbitrary"),
    ("경계점", "boundary point"),
    ("경우", "case"),
    ("사례", "case"),
    ("관측", "observation"),
    ("관측치", "observable"),
    ("종류", "kind"),
    ("순서", "order"),
    ("반복", "repetition"),
    ("유한", "finite"),
    ("무한", "infinite"),
    ("성분", "component"),
    ("추측", "conjecture"),
    ("가설", "hypothesis"),
    ("기준", "baseline"),
    ("기준점", "reference point"),
    ("기초", "base"),
    ("베이스", "base"),
    ("역할", "role"),
    ("두 개", "two"),
    ("두 축", "two axes"),
    ("두 기둥", "two pillars"),
    ("세 기둥", "three pillars"),
    ("기둥", "pillar"),
    ("방정식", "equation"),
    ("동일", "same"),
    ("단순화", "simplification"),
    ("단순", "simple"),
    ("분기", "branch"),
    ("가지", "branch"),
    ("과제", "task"),
    ("성질", "property"),
    ("성립", "holding"),
    ("다항", "polynomial"),
    ("지분", "share"),
    ("자유 조합", "free combination"),
    ("단원자", "monatomic"),
    ("마찰", "friction"),
    ("평면", "plane"),
    ("굴곡", "curvature"),
    ("순환", "cyclic"),
    ("주기적", "periodic"),
    ("수치", "numerical"),
    ("확률", "probability"),
    ("통계", "statistical"),
    ("분포", "distribution"),
    ("범위", "range"),
    ("영역", "region"),
    ("사차", "fourth"),
    ("오차", "error"),
    ("오차 0", "error 0"),
    ("자동", "auto"),
    ("외부", "external"),
    ("내부", "internal"),
    ("참조", "reference"),
    ("감지", "detect"),
    ("출력", "output"),
    ("입력", "input"),
    ("시간", "time"),
    ("공간이", "space"),
    ("위치", "position"),
    ("속도", "speed"),
    ("자유", "free"),
    ("자유롭게", "freely"),
    ("자유도는", "DOF is"),
    ("자유도의", "of DOF"),
    ("자유도가", "DOF"),
    ("표면", "surface"),
    ("부피", "volume"),
    ("질량", "mass"),
    ("모델", "model"),
    ("기준선", "baseline"),
    ("사이", "between"),
    ("서로", "each other"),
    ("상호", "mutual"),
    ("대칭성", "symmetry"),
    ("비대칭", "asymmetry"),
    ("원점", "origin"),
    ("접점", "contact"),
    ("뺄셈", "subtraction"),
    ("곱셈", "multiplication"),
    ("덧셈", "addition"),
    ("나눗셈", "division"),
    ("기대값", "expected value"),
    ("분산", "variance"),
    ("편차", "deviation"),
    ("승격", "promotion"),
    ("파동", "wave"),
    ("스위치", "switch"),
    ("게이지", "gauge"),
    ("이론", "theory"),
    ("표준", "standard"),
    ("제공", "provide"),
    ("달성", "achievement"),
    ("확립", "establishment"),
    ("확인", "confirm"),
    ("고정점", "fixed point"),
    ("또는", " or "),
    ("혹은", " or "),
    ("그리고", " and "),
    ("또한", "also"),
    ("하지만", "however"),
    ("따라서", "therefore"),
    ("이에", "therein"),
    ("이것", "this"),
    ("저것", "that"),
    ("모든", "all"),
    ("대부분", "most"),
    ("일부", "some"),
    ("전체", "whole"),
    ("전부", "all"),
    ("만큼", "as much"),
    ("정도", "degree"),
    ("이상", "or more"),
    ("이하", "or less"),
    ("초과", "exceed"),
    ("미만", "less than"),
    ("까지", "up to"),
    ("부터", "from"),
    ("아래", "below"),
    ("전기약", "electroweak"),
    ("깨짐", "breaking"),
    ("자기coupling", "self-coupling"),
    ("끈/브레인", "string/brane"),
    ("브레인", "brane"),
    ("space이", "space"),
    ("space의", "of space"),
    ("space을", "space"),
    ("space", "space"),
    ("이중항", "doublet"),
    ("성min", "component"),
    ("기각", "reject"),
    ("이탈", "drift"),
    ("본체", "body"),
    ("정직", "honest"),
    ("본문", "body text"),
    ("정식화", "formalization"),
    ("세 층", "three-layer"),
    ("층위", "tier"),
    ("층수", "layer count"),
    ("비슷", "similar"),
    ("다만", "however"),
    # General Korean particles after English word — space-bounded for safety
    (" 의 ", " of "),
    (" 를 ", " "),
    (" 을 ", " "),
    (" 는 ", " "),
    (" 은 ", " "),
    (" 도 ", " also "),
    (" 에 ", " at "),
    (" 와 ", " and "),
    (" 과 ", " and "),
    (" 로 ", " via "),
    (" 으로 ", " via "),
    (" 에서 ", " from "),
    (" 에게 ", " to "),
    # Translations for verb endings (longer first)
    ("한다.", "."),
    ("된다.", "."),
    ("이다.", "."),
    ("이며", "; "),
    ("하여", "by "),
    ("하고", "and "),
    ("한다", ""),
    ("된다", ""),
    ("이라", "is"),
    ("라고", "as"),
    ("처럼", "like"),
    ("이런", "such"),
    ("이렇게", "thus"),
    ("즉 ", "i.e. "),
    # Other common
    ("자유도는", "DOF"),
    ("분수 축 척도", "fractional axis scale"),
    ("고정점", "fixed point"),
    ("고차원", "high-dimensional"),
    ("저차원", "low-dimensional"),
    ("사각형", "square"),
    ("원형", "circle"),
    ("구형", "sphere"),
    ("유클리드", "Euclidean"),
    ("쌍곡", "hyperbolic"),
    ("쌍극자", "dipole"),
    ("양극자", "positive pole"),
    ("음극자", "negative pole"),
    ("약수의", "divisor"),
    ("약수의 합", "divisor sum"),
    ("약수의 개수", "divisor count"),
    ("제곱", "square"),
    ("세제곱", "cube"),
    ("루트", "root"),
    ("제곱근", "square root"),
    ("세제곱근", "cube root"),
    ("로그", "log"),
    ("지수함수", "exponential"),
    ("삼각함수", "trig function"),
    ("미분", "derivative"),
    ("적분", "integral"),
    ("함수", "function"),
    ("변수", "variable"),
    ("상수의", "constant's"),
    ("상수군", "constant family"),
    ("정수", "integer"),
    ("실수", "real number"),
    ("유리수", "rational"),
    ("무리수", "irrational"),
    ("소수", "prime"),
    ("홀수", "odd"),
    ("짝수", "even"),
    # Korean that might remain (punctuation-sensitive)
    ("이 도메인", "this domain"),
    ("이 문서", "this document"),
    ("본 도메인", "this domain"),
    ("본 문서", "this document"),
    ("다음 표", "the table below"),
    ("다음", "next"),
    ("아래 표", "the table below"),
    ("아래", "below"),
    ("위 표", "the table above"),
    ("위의", "the above"),

    # File-unique patterns
    (" 의미", " meaning"),
    ("의미", "meaning"),
    ("해를", "the solution"),
    ("해법", "method"),
    ("해결", "addressing"),
    ("계열", "family"),
    ("변형", "variant"),
    ("중심", "center"),
    ("원인", "cause"),
    ("결과", "result"),
    ("규모", "scale"),
    ("차이", "difference"),
    ("동일성", "identity"),
    ("항등", "identity"),
    ("일반화", "generalization"),
    ("특수", "special"),
    ("특수화", "specialization"),
    ("축소", "reduction"),
    ("확대", "enlargement"),
    ("조건식", "condition equation"),
    ("형태", "shape"),
    ("모양", "shape"),
    ("곡선", "curve"),
    ("지수가", "exponent"),
    ("주체", "subject"),
    ("객체", "object"),
    ("대상", "target"),
    ("단계", "tier"),
    ("단일", "single"),
    ("다중", "multiple"),
    ("모듈", "module"),
    ("상세", "detailed"),
    ("개요", "overview"),
    ("하나", "one"),
    ("여섯", "six"),
    ("일곱", "seven"),
    ("여덟", "eight"),
    ("아홉", "nine"),
    ("자연수", "natural number"),
    # (single-char safe ops last)
    ("이다", ""),
]


# Per-file Korean title -> English title map. The title appears in the H1,
# in several ASCII-art headers, and inline in prose. Every substitution is
# an exact string match (no regex).
TITLES: dict[str, tuple[str, str]] = {
    "domains/physics/millennium-poincare/millennium-poincare.md": (
        "푸앵카레 추측 (HEXA-POINCARE)", "Poincare Conjecture (HEXA-POINCARE)"),
    "domains/physics/millennium-yang-mills/millennium-yang-mills.md": (
        "양-밀스 질량 간격 (HEXA-YM)", "Yang-Mills Mass Gap (HEXA-YM)"),
    "domains/physics/millennium-p-vs-np/millennium-p-vs-np.md": (
        "P vs NP (HEXA-PNP)", "P vs NP (HEXA-PNP)"),
    "domains/physics/millennium-riemann/millennium-riemann.md": (
        "리만 가설 (HEXA-RIEMANN)", "Riemann Hypothesis (HEXA-RIEMANN)"),
    "domains/physics/millennium-hodge/millennium-hodge.md": (
        "호지 추측 (HEXA-HODGE)", "Hodge Conjecture (HEXA-HODGE)"),
    "domains/physics/millennium-navier-stokes/millennium-navier-stokes.md": (
        "나비에-스토크스 (HEXA-NS)", "Navier-Stokes (HEXA-NS)"),
    "domains/physics/millennium-bsd/millennium-bsd.md": (
        "버치-스위너턴다이어 (HEXA-BSD)", "Birch-Swinnerton-Dyer (HEXA-BSD)"),
    "domains/physics/pure-mathematics/pure-mathematics.md": (
        "순수수학 (HEXA-PURE-MATH)", "Pure Mathematics (HEXA-PURE-MATH)"),
    "domains/physics/topology/topology.md": (
        "위상수학 (HEXA-TOPOLOGY)", "Topology (HEXA-TOPOLOGY)"),
    "domains/physics/holography/holography.md": (
        "홀로그래피 (HEXA-HOLO)", "Holography (HEXA-HOLO)"),
    "domains/physics/hexa-topo/hexa-topo.md": (
        "n=6 위상 (HEXA-TOPO)", "n=6 Topology (HEXA-TOPO)"),
    "domains/physics/cosmology/cosmology.md": (
        "궁극의 우주론 (HEXA-COSMO)", "Ultimate Cosmology (HEXA-COSMO)"),
    "domains/physics/cosmology-particle/cosmology-particle.md": (
        "입자 우주론 (HEXA-PARTICLE-COSMO)", "Particle Cosmology (HEXA-PARTICLE-COSMO)"),
    "domains/physics/particle-cosmology/particle-cosmology.md": (
        "입자-우주론 결합 (HEXA-PART-COSMO)", "Particle-Cosmology Coupling (HEXA-PART-COSMO)"),
    "domains/physics/higgs/higgs.md": (
        "힉스 메커니즘 (HEXA-HIGGS)", "Higgs Mechanism (HEXA-HIGGS)"),
    "domains/physics/gravity-wave/gravity-wave.md": (
        "중력파 (HEXA-GW)", "Gravity Wave (HEXA-GW)"),
    "domains/physics/quantum-oracle/quantum-oracle.md": (
        "양자 오라클 (HEXA-QORACLE)", "Quantum Oracle (HEXA-QORACLE)"),
    "domains/physics/simulation-theory/simulation-theory.md": (
        "시뮬레이션 이론 (HEXA-SIM)", "Simulation Theory (HEXA-SIM)"),
}


def translate_file(p: Path, extra: list[tuple[str, str]] | None = None) -> tuple[int, int]:
    """Apply all pairs to file. Return (chars_before, chars_after) in CJK range."""
    text = p.read_text(encoding="utf-8")
    before = len(text)
    pairs = list(PAIRS)
    if extra:
        pairs.extend(extra)
    # File-specific title substitution
    title_key = str(p).split("n6-architecture/", 1)[-1]
    if title_key in TITLES:
        ko, en = TITLES[title_key]
        pairs.append((ko, en))
    for k, v in pairs:
        if k in text:
            text = text.replace(k, v)
    # Post-fix: collapse `σ(6)합=12` remnants (Korean "합" = "sum")
    text = text.replace("σ(6)합=12", "sigma(6)sum=12")
    p.write_text(text, encoding="utf-8")
    return before, len(text)


CJK_RE = re.compile(r"[ᄀ-ᇿ぀-ヿㄱ-ㆎ㐀-䶿一-鿿가-힣豈-﫿]")


def cjk_count(p: Path) -> int:
    return len(CJK_RE.findall(p.read_text(encoding="utf-8")))


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: phase6_b7_translate.py <file> [<file> ...]", file=sys.stderr)
        return 2
    for arg in argv[1:]:
        p = Path(arg)
        before_cjk = cjk_count(p)
        translate_file(p)
        after_cjk = cjk_count(p)
        print(f"{arg}: CJK {before_cjk} -> {after_cjk}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
